name: Connect to VPN and deploy on production server
on: [push]
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Connect and Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #setenv
      - name: Set Variables
        uses: allenevans/set-env@v2.0.0
        with:
          OVPN: ${{ secrets.OVPN }}
      #write vpn files
      - name: Write VPN Files
        run: |
          mkdir ~/.ssh
          echo "$OVPN" > .github/vpn.ovpn
      #install ovpn
      - name: Install OpenVPN
        run: |
          sudo apt install apt-transport-https
          sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
          sudo apt-key add openvpn-repo-pkg-key.pub
          sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-bionic.list
          sudo apt update
          sudo apt install openvpn3
      #start vpn
      - name: Start OpenVPN
        run: openvpn3 session-start --config .github/vpn.ovpn
      #deploy 
      - name: Deploy files to production
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.USERNAME }}
          server: '10.8.0.1'
          ssh_private_key: ${{ secrets.SSH_PPK }} 
          local_path: './*'
          remote_path: '/var/www/orario.mrbackslash.it/public-html'
          args: '-o ConnectTimeout=5'